### ISSUE TITLE
Failed Scan

### ISSUE THREAD

**Issue by JasonMorgan** [virtmerlin/harbor-image-resource#1]
Hello! 

One: thank you for this, very useful and I'm excited to use it to showcase Harbor with Concourse.

Two: I'm unable to get the scan functionality to work.  I get the following error from concourse when I try and use the scan `https://harbor.gcp.59s.io/api/repositories/harbor.gcp.59s.io%2F59s%2Fadsb-sync/tags/latest`.

I have the resource configured as follows in my pipeline.yml:

```
- name: docker-image
  type: harbor-image
  source:
    username: ((harbor.username))
    password: ((harbor.password))
    skip_pull: true
    repository: harbor.gcp.59s.io:443/59s/adsb-sync
    harbor_host: harbor.gcp.59s.io
    harbor_image: harbor.gcp.59s.io/59s/adsb-sync
    harbor_trigger_scan: true
    harbor_scan_thresholds:  [{"severity": 1,"count": 20},{"severity": 2,"count": 20}]
    notary_enable: false
    insecure_registries: ["harbor.gcp.59s.io:443"]
```

I tried to recreate the call at the cli on my own machine and got back a 404. When I look at the swagger docs for harbor it looks like the url for initiating a scan is different. `/repositories/{repo_name}/tags/{tag}/scan`

Anyway, not sure what to do but would love to get this working.
